import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col items-center'>
        <div>Hello Next js</div>
        <div>Hello Next js</div>
      </div>

     
    </>
  )
}
